package com.example.demo.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * 公务员实体类
 */
@Entity
@Table(name = "employee") //@Entity, @Table(name="") 一般用于jpa，这两个注解一块使用，但是如果表名和实体类名相同的话，@Table可以省略。
public class Employee implements Serializable  {

    /**
     * @GeneratedValue 为一个实体生成一个唯一标识的主键、@GeneratedValue提供了主键的生成策略。
     *
     * @GeneratedValue(strategy = GenerationType.SEQUENCE,generator = “repair_seq”)：
     *      表示主键生成策略是sequence（可以为Auto、IDENTITY、native等，Auto表示可在多个数据库间切换），指定sequence的名字是repair_seq。
     *
     * @GeneratedValue 注解有两个属性,分别是strategy和generator,
     *  generator 属性的值是一个字符串,默认为"",其声明了主键生成器的名称 (对应于同名的主键生成器@SequenceGenerator和@TableGenerator)。
     *  strategy属性：提供四种值:
     * 		-AUTO 主键由程序控制, 是默认选项 ,不设置就是这个。
     * 		-IDENTITY 主键由数据库生成, 采用数据库自增长, Oracle不支持这种方式	（id bigint generated by default as identity,...)
     * 		-SEQUENCE 通过数据库的序列产生主键, MYSQL 不支持。
     * 			根据底层数据库的序列来生成主键，条件是数据库支持序列。 这个值要与generator一起使用，generator 指定生成主键使用的生成器（可能是orcale中自己编写的序列）。
     * 		-Table 使用一个特定的数据库表格来保存主键。提供特定的数据库产生主键, 该方式更有利于数据库的移植。
     *
     * 注意：默认SpringBoot的@GeneratedValue 是不需要加参数的,但是如果数据库控制主键自增(auto_increment), 不加参数就会报错
     *
     *  扩展：
     *     @SequenceGeneretor(name = “repair_seq”, sequenceName = “seq_repair”, allocationSize = 1)：
     *          name为sequence的名称，以便使用，sequenceName为数据库的sequence名称，两个名称可以一致。
     *
     */
    @Id //表示该属性为主键。
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false, unique = true, columnDefinition="bigint(19) COMMENT '主键'")
    private Long id;
    /**
     * 姓名
     */
    @Column(columnDefinition="varchar(50) COMMENT '姓名'") //如果字段名与列名相同，则可以省略。 columnDefinition:自动生成表时列的说明
    private String name;
    /**
     * 性别
     */
    @Column(columnDefinition="varchar(10) COMMENT '性别'")
    private String gender;
    /**
     * 出生年月
     */
    @Column(columnDefinition="date COMMENT '出生年月'")
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8") //后台到前台的时间格式的转换
    @DateTimeFormat(pattern = "yyyy-MM-dd") //或 @DateFormat 前后到后台的时间格式的转换
    private Date birthday;
    /**
     * 民族
     */
    @Column(columnDefinition="varchar(20) COMMENT '民族'")
    private String nation;
    /**
     * 籍贯
     */
    @Column(columnDefinition="varchar(200) COMMENT '籍贯'")
    private String nativeplace;
    /**
     * 出生地
     */
    @Column(nullable = true, unique = false,  columnDefinition="varchar(200) COMMENT '出生地'")
    private String birthplace;
    /**
     * 身份证号
     */
    @Column(nullable = true, unique = false,  columnDefinition="varchar(20) COMMENT '身份证号'")
    private String idcard;
    /**
     * 参加工作时间
     */
    @Column(name="work_time", columnDefinition="date COMMENT '参加工作时间'")
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date workTime;
    /**
     * 政治面貌
     */
    @Column(name="politics_status", columnDefinition="varchar(50) COMMENT '政治面貌'")
    private String politicsStatus;
    /**
     * 学历学位
     */
    @Column(columnDefinition="varchar(50) COMMENT '学历学位'")
    private String education;
    /**
     * 工作单位
     */
    @Column(name="work_unit", columnDefinition="varchar(200) COMMENT '工作单位'")
    private String workUnit;
    /**
     * 职位职级
     */
    @Column(name="position_rank", columnDefinition="varchar(100) COMMENT '职位职级'")
    private String positionRank;
    /**
     * 授予奖励
     */
    @Column(name="grant_rewards", columnDefinition="varchar(500) COMMENT '授予奖励'")
    private String grantRewards;
    /**
     * 奖励情况
     */
    @Column(name="honors_awards", columnDefinition="varchar(1000) COMMENT '奖励情况'")
    private String honorsAwards;
    /**
     * 简历
     */
    @Column(columnDefinition="varchar(5000) COMMENT '简历'")
    private String resume;
    /**
     * 创建时间
     */
    @Column(name="create_time", columnDefinition="datetime COMMENT '创建时间'")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;
    /**
     * 修改时间
     */
    @Column(name="update_time", columnDefinition="datetime COMMENT '修改时间'")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getNation() {
        return nation;
    }

    public void setNation(String nation) {
        this.nation = nation;
    }

    public String getNativeplace() {
        return nativeplace;
    }

    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    public String getBirthplace() {
        return birthplace;
    }

    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    public String getIdcard() {
        return idcard;
    }

    public void setIdcard(String idCard) {
        this.idcard = idCard;
    }

    public Date getWorkTime() {
        return workTime;
    }

    public void setWorkTime(Date workTime) {
        this.workTime = workTime;
    }

    public String getPoliticsStatus() {
        return politicsStatus;
    }

    public void setPoliticsStatus(String politicsStatus) {
        this.politicsStatus = politicsStatus;
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getWorkUnit() {
        return workUnit;
    }

    public void setWorkUnit(String workUnit) {
        this.workUnit = workUnit;
    }

    public String getPositionRank() {
        return positionRank;
    }

    public void setPositionRank(String positionRank) {
        this.positionRank = positionRank;
    }

    public String getGrantRewards() {
        return grantRewards;
    }

    public void setGrantRewards(String grantRewards) {
        this.grantRewards = grantRewards;
    }

    public String getHonorsAwards() {
        return honorsAwards;
    }

    public void setHonorsAwards(String honorsAwards) {
        this.honorsAwards = honorsAwards;
    }

    public String getResume() {
        return resume;
    }

    public void setResume(String resume) {
        this.resume = resume;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", gender='" + gender + '\'' +
                ", birthday=" + birthday +
                ", nation='" + nation + '\'' +
                ", nativeplace='" + nativeplace + '\'' +
                ", birthplace='" + birthplace + '\'' +
                ", idcard='" + idcard + '\'' +
                ", workTime=" + workTime +
                ", politicsStatus='" + politicsStatus + '\'' +
                ", education='" + education + '\'' +
                ", workUnit='" + workUnit + '\'' +
                ", positionRank='" + positionRank + '\'' +
                ", grantRewards='" + grantRewards + '\'' +
                ", honorsAwards='" + honorsAwards + '\'' +
                ", resume='" + resume + '\'' +
                '}';
    }


}
